---
layout: single
title: "Java Exception"
toc: true
toc_sticky: true
categories: JAVA
tag: [JAVA, Exception]
author_profile: false
sidebar:
    nav: "docs"
---

# Exception
---

## 1. 예외(Exception)란?
자바에서 예외는 프로그램 실행 중 발생하는 예상치 못한 오류로, <br/>
프로그램의 흐름을 중단시키거나 비정상 종료로 이어질 수 있는 문제 상황을 말한다.<br/>
예외 처리를 통해 프로그램이 예외 상황에서도 정상적으로 종료될 수 있도록 조치할 수 있다.<br/>

**Error와 Exception의 차이**
- **Error**: 시스템 문제나 심각한 하드웨어 오동작으로 인해 발생하는 오류. <br/>
 복구할 수 없으며, 발생 시 프로그램은 강제 종료된다. (`OutOfMemoryError` 등)<br/>
- **Exception**: 사용자의 잘못된 입력, 개발자의 코딩 실수 등으로 발생하며, <br/>
 예외 처리를 통해 프로그램을 복구하고 정상적인 실행 상태로 돌아갈 수 있다.<br/>

## 2. 예외의 종류
1. **일반 예외**
   - 컴파일 시점에서 예외 처리 코드가 없는 경우 컴파일 오류가 발생한다.<br/>
   - 예: `IOException`, `SQLException`<br/>
2. **실행 예외**
   - 컴파일 시 예외 처리 코드가 없어도 컴파일이 되지만, 실행 중에 예외가 발생할 수 있다.<br/>
   - 예: `ArithmeticException`, `NullPointerException`<br/>

## 3. 예외 처리의 목적
예외 처리는 프로그램이 예상치 못한 오류로 인해 중단되지 않도록 방지하고,<br/>
예외 상황이 발생했을 때 프로그램이 안전하게 종료되거나 예외 상황에 대해 올바르게 대응하도록 하는 장치.<br/>


## 4. 예외 처리 구문
1. try-catch-finally 구문
    `try-catch-finally` 구문은 예외가 발생할 가능성이 있는 코드를 감싸고, <br/>
    예외 발생 시 특정 코드를 실행하도록 한다. <br/>
    `finally` 블록은 예외 발생 여부와 관계없이 항상 실행된다.

    ```java
    try {
        // 예외가 발생할 가능성이 있는 코드
    } catch (예외 클래스 참조변수) {
        // 예외가 발생한 경우 실행되는 코드
        // 참조변수는 예외와 관련된 정보를 담고 있음
    } finally {
        // 예외 발생 여부와 상관없이 항상 실행되는 코드 (생략 가능)
    }
    ```
    
    ```java
    public class ExceptionExample {
        public static void main(String[] args) {
            try {
                int result = 10 / 0; // ArithmeticException 발생
            } catch (ArithmeticException e) {
                System.out.println("예외 발생: " + e.getMessage());
            } finally {
                System.out.println("예외 처리 완료 후 실행되는 finally 블록");
            }
        }
    }
    ```
2. 다중 catch문
    다중 `catch`문을 통해 여러 종류의 예외를 각각 다른 방식으로 처리할 수 있다.<br/>
    예외 클래스는 상위에서 하위로 나열해야 하며, 가장 상위 예외인 `Exception` 클래스는 마지막에 배치한다.<br/>

    ```java
    try {
        // 예외가 발생할 가능성이 있는 코드
    } catch (IOException e) {
        // IOException 처리 코드
    } catch (ArithmeticException e) {
        // ArithmeticException 처리 코드
    } catch (Exception e) {
        // 모든 예외 처리 코드
    }
    ```

## 5. throw와 throws
1. throw
    `throw` 키워드는 특정 예외를 강제로 발생시킬 때 사용한다.<br/>

    ```java
    public class ThrowExample {
        public static void main(String[] args) {
            try {
                checkAge(15); // 나이가 18 미만이므로 예외 발생
            } catch (Exception e) {
                System.out.println("예외 발생: " + e.getMessage());
            }
        }

        public static void checkAge(int age) {
            if (age < 18) {
                throw new IllegalArgumentException("나이는 18 이상이어야 합니다.");
            }
            System.out.println("나이가 적절합니다.");
        }
    }
    ```

2. throws
    `throws` 키워드는 메서드에서 발생할 수 있는 예외를 호출한 쪽으로 넘기는 역할을 한다.<br/>
    예외 처리를 호출한 메서드에서 해야 한다.<br/>

    ```java
    public class ThrowsExample {
        public static void main(String[] args) {
            try {
                readFile();
            } catch (IOException e) {
                System.out.println("예외 발생: " + e.getMessage());
            }
        }

        public static void readFile() throws IOException {
            throw new IOException("파일을 읽는 중 오류 발생");
        }
    }
    ```

## 6. 자주 사용되는 예외 클래스
1. ArithmeticException
   - 숫자를 0으로 나눌 때 발생한다.
2. NullPointerException
   - 참조 변수에 null 값이 할당된 경우, 해당 변수를 통해 접근하려고 할 때 발생한다.
3. ArrayIndexOutOfBoundsException
   - 배열의 범위를 벗어난 인덱스에 접근하려고 할 때 발생한다.
4. ClassCastException
   - 잘못된 객체 캐스팅 시 발생한다.
5. IOException
   - 파일 입출력 오류가 발생할 때 발생한다.
6. SQLException
   - 데이터베이스 접근 오류 시 발생한다.
7. FileNotFoundException
   - 파일이 존재하지 않을 때 발생한다.

## 7. 예외 처리의 추가적인 내용
1. 예외 전환(Exception Wrapping)
        기존의 예외를 다른 예외로 변환하여 호출자에게 더 명확한 정보를 제공할 수 있다.<br/>
        예외 전환을 통해 특정한 예외 상황을 포착하고 다른 예외로 변환하여 관리하기 쉽게 만든다.<br/>

        ```java
        public void method() {
            try {
                // 예외 발생 가능 코드
            } catch (IOException e) {
                throw new RuntimeException("파일 처리 중 문제 발생", e);
            }
        }
        ```

2. 사용자 정의 예외
    필요에 따라 예외 클래스를 직접 정의하여 사용할 수 있다.<br/>
    사용자 정의 예외는 `Exception` 클래스를 상속하여 생성한다.<br/>

    ```java
    class CustomException extends Exception {
        public CustomException(String message) {
            super(message);
        }
    }

    public class CustomExceptionExample {
        public static void main(String[] args) {
            try {
                throwCustomException();
            } catch (CustomException e) {
                System.out.println("예외 발생: " + e.getMessage());
            }
        }

        public static void throwCustomException() throws CustomException {
            throw new CustomException("사용자 정의 예외 발생");
        }
    }
    ```


